=== s184616/Moje_hobby/184616_Rykowska_Aleksandra_1/main.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	
	<xs:element name="Aktywnosc" >
		<xs:complexType >
			<xs:sequence>
				<xs:element ref="autor"/>
				<xs:element name="strony" type="stronyType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="zdjecia" type="zdjeciaType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="linki" type="linkiType" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="tabele" type="tabeleType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="autor" type="autorType" />
	<xs:complexType name="autorType">
		<xs:sequence>
			<xs:element name="imie" type="shortStringType" />
			<xs:element name="nazwisko" type="longStringType" />
		</xs:sequence>
		<xs:attribute ref="jezyk"/>
	</xs:complexType>
	
		<xs:simpleType name="shortStringType">
			<xs:restriction base="xs:string">
				<xs:maxLength value="30"/>
			</xs:restriction>
		</xs:simpleType>
		<xs:simpleType name="longStringType">
			<xs:restriction base="xs:string">
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
		
		<xs:attribute name="jezyk" default="PL">
			<xs:simpleType>
				<xs:union memberTypes="jezykType shortStringType" />
			</xs:simpleType>
		</xs:attribute>
			
		<xs:simpleType name="jezykType">
			<xs:restriction base="xs:string">
				<xs:pattern value="([A-Z])*" />
			</xs:restriction>
		</xs:simpleType>
			
			
	<xs:complexType name="stronyType">
		<xs:sequence>
			<xs:element ref="strona" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
		<xs:element name="strona">
			<xs:complexType>
				<xs:sequence>
					<xs:element ref="tytul" />
					<xs:element ref="tekst" />
				</xs:sequence>
			<xs:attribute ref="o"/>
			</xs:complexType>
		</xs:element>
		
		<xs:element name="tytul" >
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="5"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>

		<xs:element name="tekst">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="15"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		
		<xs:attribute name="o" type="oType"/>
		
		<xs:simpleType name="oType">
			<xs:restriction base="xs:string">
				<xs:enumeration value="Moje hobby" />
				<xs:enumeration value="Sport" />
				<xs:enumeration value="Muzyka" />
				<xs:enumeration value="Wolontariat" />
				<xs:enumeration value="Ankieta" />
			</xs:restriction>
		</xs:simpleType>
	
	
	<xs:complexType name="zdjeciaType">
		<xs:sequence>
			<xs:element ref="obraz" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="obraz" type="obrazType" />
	
		<xs:complexType name="obrazType">
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="rodzaj" type="xs:string"/>
					<xs:attribute ref="src"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
		
		<xs:attribute name="src" type="xs:anyURI"/>
	
	
	<xs:complexType name="linkiType">
		<xs:sequence>
			<xs:element ref="link" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
		<xs:element name="link" >
			<xs:complexType >
				<xs:simpleContent>
					<xs:extension base="xs:string">
						<xs:attribute ref="src"/>
					</xs:extension>
				</xs:simpleContent>
			</xs:complexType>
		</xs:element>
	
	
	<xs:complexType name="tabeleType">
		<xs:sequence>
			<xs:element name="tabela" type="tabelaType" minOccurs="0" maxOccurs="100" />
		</xs:sequence>
	</xs:complexType>
	
		<xs:complexType name="tabelaType">
			<xs:sequence>
				<xs:element name="wiersz" minOccurs="0" maxOccurs="100">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="kolumna" type="xs:string" minOccurs="0" maxOccurs="100" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attributeGroup ref="tabela"/>
		</xs:complexType>

		<xs:attributeGroup name="tabela">
  			<xs:attribute name="id" type="xs:byte" />
			<xs:attribute name="wiersze" type="iloscType" />
			<xs:attribute name="kolumny" type="iloscType" />
		</xs:attributeGroup>

		
		<xs:simpleType name="iloscType">
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
				<xs:maxInclusive value="100"/>
			</xs:restriction>
		</xs:simpleType>
		
</xs:schema>

=== s184616/Moje_hobby/184616_Rykowska_Aleksandra_1/main.xml
<?xml version="1.0" encoding="utf-8"?>
<Aktywnosc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="main.xsd">
   
	<autor jezyk="polski">
		<imie>Aleksandra</imie>
		<nazwisko>Rykowska</nazwisko>
	</autor>
	
	<strony>
		<strona o="Moje hobby">
			<tytul>Aktywność</tytul>
			<tekst>
				Witam na mojej stronie !
				Możesz przeczytać tutaj o moim hobby, które nazwałam "Aktywność". Moje zainteresowania są dosyć róźnorodne i często się zmieniają, dlatego postanowiłam opisać parę z nich i połączyć w jedno. Moja działalność dzieli się na sport, muzyke i wolontariat. Brałam udział też np. w występach, chodziłam do kółka teatralnego i interesował mnie taniec, ale był to na tyle krótki epizod, że skupię się na głównych elementach :). Wszystkie te rzeczy towarzyły mi na pewnych etapach mojego życia, a teraz podzielę się nimi tutaj na stronie.
				Zapraszam !
			</tekst>
		</strona>
		
		<strona o="Sport">
			<tytul>Sport</tytul>
			<tekst>
				Narty
					Na nartach jeździłam co ferie, z małymi przerwami, odkąd miałam parenaście lat z moim obozem na Kubiesówke. Poznałam tam mnóstwo ludzi i bardzo dobrze wpominam ten czas. Co wieczór graliśmy w różne gry obozowe, rano jechaliśmy na stok, przez pare godzin zjeżdżaliśmy, a potem wspinaliśmy się do naszego domku. Jazdę na nartach polecam każdemu kto jeszcze nie próbował, bo wrażenia są niezapomniane.
				Snowboard
					Na snowbordzie zaczęłam się uczyć jeździć od niedawna, rok po nartach i dopiero przez jedne ferie. Mimo, że upadki są bardziej bolesne i jest więcej siniaków to kiedy już się załapie sposób jeżdżenia to jest to bardzo ciekawe doświadczenie i myślę, że chciałabym w przyszłości kontynuować nauke dalej.
				Łyżwy
					Uwielbiam również bardzo jeździć na łyżwach. Uczyłam się na nich pierwszy raz jeździć w podstawówce i od tego momentu jak mam okazję wspólnie ze znajomymi wychodzimy wspólnie pojeździć :)
				Rolki
					Dzięki temu, że nauczyłam się jeździć dobrze na łyżwach, polubiłam bardzo jeźdżenie na rolkach. Brałam nawet udział z moją koleżanką w wydarzeniach, gdzie duża grupa ludzi jeździła razem przez miasto po ulicach na specjalnie wyznaczonych trasach.
				Rower
					Nie mogło też zabraknąć jeżdżenia na rowerze. Jest to idealne zajęcie na wolny, słoneczny dzień, kiedy można się trochę odprężyć i nie myśleć o innych sprawach. A najlepiej się jeździ razem :)
				Ćwiczenia i rozciąganie
					Od momentu gdy zaczęła się pandemia i nie można było wychodzić, uznałam, że jest to idealny czas na ćwiczenia we własnym domu. Znajdywałam wtedy plan ćwiczeń według, którego postępowałam, a potem dołożyłam do tego rozciąganie, które bardzo pomagało, kiedy przez dłuższy czas siedziało się przy komputerze i uczyło.
				I inne ...
					Na pewno było jeszcze wiele innych dziedzin sportu, które uprawiałam, np. basen, golf i tym podobne, ale są to raczej poboczne hobby, a najważniejsze wypisałam wyżej :) 
			</tekst>
		</strona>
		
		<strona o="Muzyka">
			<tytul>Muzyka</tytul>
			<tekst>
					Kolejnym z moich zainteresowań jest muzyka, która interesowała mnie od zawsze, ponieważ uwielbiam śpiewać, poznawać nowe piosenki i jestem otwarta na wiele gatunków. Mogę jej słychać gdy mi smutno, źle, kiedy pracuję, dosłownie w każdym momencie i dzięki niej czuję się lepiej. Jednak wszystko się zaczęło od gitary.
				Gitara
					Kiedy miałam może parenaście lat dostałam na święta gitarę. Na początku oczywiście nie potrafiłam grać. Przez dłuższy czas korzystał z niej bardziej tata, jednak w gimnazjum miałam okazję zacząć. Uczyliśmy się przez rok grać na gitarze na lekcji muzyki, a pod koniec ostatnią piosenką do zagrania i zaśpiewania na raz była "Ostatnia nocka" Yugopolis and Maciej Maleńczuk. Nie zostałam wtedy nagrana, ale brzmiało to mniej więcej tak: Ostatnia nocka na gitarze . Niestety poźniej nie miałam za bardzo czasu kontynuować naukę, ale rozważam powrót i próbę grania na nowo.
				Ukulele
					Następnym instrumentem, który bardzo mnie ciekawił było ukulele. Zawsze podobało mi się to jakie jest ono proste i jak ładnie potrafi brzmieć. Nie miałam niestety wcześniej tego instrumentu, aż do momentu pożyczenia go na studiach. Uwierzyłam w możliwość szybkiej nauki na nim, dzięki temu filmikowi: 20h z Ukulele i zamierzam spełnić ten cel :)
			</tekst>
		</strona>
		
		<strona o="Wolontariat">
			<tytul>Wolontariat</tytul>
			<tekst>
					Jako ostatnie zainteresowanie opowiem o moim udziale w wolontariacie.
				Dziewczynka z zapałkami
					Był to jeden z moich pierwszych wolontariatów w gimnazjum, od którego mogła nawet się zacząć moja prygoda z pomaganiem. Polegało ono na tym, że przychodziłam do jednego z większych sklepów, pomagałam pakować ludzią zakupy, a w zamian dawałam im zapałkę.
				Run Toruń
					W Run Toruń brałam udział parę razy jaka wolontariuszka i zajmowałam się różnymi rzeczami. Raz ustawiałam pachołki i oznaczałam trasę, innym razem przygotowywałam stoiska, jeszcze innym trzymałam wodę dla biegaczy, nakładałam im medale na szyje i wiele wiele innych, ale za każdym razem towarzyszyła mi radość z pomocy i udzielania się społecznie. W tym roku tak wyglądał bieg: Run Toruń 2020
				Szukanie dawcy szpiku
					Gdy postanowiłam przyłączyć się w liceum do pomocy nie byłam pełnoletnia, więc nie mogłam wykonywać ważniejszych zadań, ale miałam swój mały udział i roznosiłam po galerii handlowej ulotki i balony, opowiadając o akcji szukania dawcy szpiku dla kolegi, Jarka. Nie zawsze udawało się przekonywać ludzi do pomocy, ale zawsze było warto próbować, ponieważ ostatecznie udało się znaleźć dawcę :) Dlatego cieszę się, że miałam w tym swój udział.
				Wyprowadzanie psów ze schroniska
					W pewnym momencie razem z moją przyjaciółką postanowiłyśmy razem pomóc w schronisku i miałyśmy okazję wyprowadzać psy, które zostały porzucone i przywiązane do drzewa. Szczeniaki były bardzo wychudzone, ale miały energię, żeby wyjść na spacer. Ich widoczne szczęście z tego chwilowego wyjścia było niezapomniane.
			</tekst>
		</strona>
		
		<strona o="Ankieta">
			<tytul>Ankieta</tytul>
			<tekst>
				A teraz chciałabym się dowiedzieć coś o tobie :) Zachęcam do wypełnienia poniższej ankiety
				Dzisiejsza data:
				Imię:
				Nazwisko:
				Płeć:
				* Mężczyzna
				* Kobieta
				Czy masz hobby ?
				* Tak
				* Nie
				Jeśli tak, ile czasu na nie poświęcasz ?
				Jakie masz hobby ?
				* Sport
				* Książki
				* Motoryzacja
				* Muzyka
				* Moda
				* Fotografia
				* Malarstwo
				* Gry
				* Szydełkowanie
				* Inne
				Dodatkowy komentarz o zainteresowaniach:
			</tekst>
		</strona>
	</strony>
   
	<zdjecia>
		<obraz rodzaj="śnieżynki" src="Galeria/snowflakes.svg">śnieżynki</obraz>
		<obraz rodzaj="narty" src="Galeria/narty1.jpg">narty1</obraz>
		<obraz rodzaj="narty" src="Galeria/narty2.jpg">narty2</obraz>
		<obraz rodzaj="snowboard" src="Galeria/snowboard1.jpg">snowboard1</obraz>
		<obraz rodzaj="snowboard" src="Galeria/snowboard2.jpg">snowboard2</obraz>
		<obraz rodzaj="łyżwy" src="Galeria/lyzwy1.jpg">łyżwy1</obraz>
		<obraz rodzaj="łyżwy" src="Galeria/lyzwy2.jpg">łyżwy2</obraz>
		<obraz rodzaj="rower" src="Galeria/bike.gif">rower</obraz>
	</zdjecia>
	
	<linki>
		<link src="https://www.youtube.com/watch?v=xUZFsxJ-4YY">Ostatnia nocka na gitarze</link>
		<link src="https://youtu.be/5MgBikgcWnY?t=892">20h z Ukulele</link>
		<link src="https://www.youtube.com/watch?v=2tnM_hX4fS0">Run Toruń 2020</link>
		<link src="https://www.youtube.com/watch?v=lJUIDBBqJOE">30 MIN FULL BODY STRETCHING</link>
	</linki>
	
	<tabele>
		<tabela id="1" wiersze="5" kolumny="2">
			<wiersz>
				<kolumna>Czy masz hobby ?</kolumna>
			</wiersz>
			<wiersz>
				<kolumna>Tak</kolumna>
				<kolumna>45%</kolumna>
			</wiersz>
			<wiersz>
				<kolumna>Nie</kolumna>
				<kolumna>23%</kolumna>
			</wiersz>
			<wiersz>
				<kolumna>Trudno powiedzieć</kolumna>
				<kolumna>21%</kolumna>
			</wiersz>
			<wiersz>
				<kolumna>Nie mam hobby</kolumna>
				<kolumna>11%</kolumna>
			</wiersz>
		</tabela>
		<tabela id="2" wiersze="5" kolumny="2">
			<wiersz>
				<kolumna>Ile czasu poświęcasz na hobby ?</kolumna>
			</wiersz>
			<wiersz>
				<kolumna>Za dużo</kolumna>
				<kolumna>10%</kolumna>
			</wiersz>
			<wiersz>
				<kolumna>W sam raz</kolumna>
				<kolumna>49%</kolumna>
			</wiersz>
			<wiersz>
				<kolumna>Za mało</kolumna>
				<kolumna>33%</kolumna>
			</wiersz>
			<wiersz>
				<kolumna>Trudno powiedzieć</kolumna>
				<kolumna>8%</kolumna>
			</wiersz>
		</tabela>
	</tabele>
	
</Aktywnosc>
